#include $(TOP)/.config

all:

install: all
	install -d $(INSTALLDIR)/usr/sbin
	install -D usr/sbin/icon.ico $(INSTALLDIR)/usr/sbin/icon.ico
	install -D usr/sbin/lld2d $(INSTALLDIR)/usr/sbin/lld2d
	install -D usr/sbin/lld2d.conf $(INSTALLDIR)/usr/sbin/lld2d.conf
	install -D usr/sbin/wrt54g.large.ico $(INSTALLDIR)/usr/sbin/wrt54g.large.ico
	install -D usr/sbin/wrt54g.small.ico $(INSTALLDIR)/usr/sbin/wrt54g.small.ico

clean:

