





install: 
	install -D portrd $(INSTALLDIR)/usr/sbin/portrd
	$(STRIP) $(INSTALLDIR)/usr/sbin/portrd
	install -D usb_wlc_status $(INSTALLDIR)/usr/sbin/usb_wlc_status
	$(STRIP) $(INSTALLDIR)/usr/sbin/usb_wlc_status

vpath %.c $(TOP)/vod

all: 

clean:


